import './alive.scss';
import './_var.scss';
import './_animate.scss';
import './maize.scss';
export { default as Switch } from './Switch/Switch.vue';
export { default as Button } from './Button/Button.vue';
export { default as Tabs } from './Tab/Tabs.vue';
export { default as TabBox } from './Tab/TabBox.vue';
export { default as Dialog } from './Dialog/Dialog.vue';
export { $Dialog as $Dialog } from './openDialog';
